import re
from fpdf import FPDF
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        # Header banner styling
        self.set_fill_color(20, 25, 35)  # Matches Streamlit dark cards
        self.rect(0, 0, 210, 35, 'F')
        
        # Medical cross logo indicator
        self.set_fill_color(78, 140, 255) # HIA primary blue
        self.rect(15, 10, 3, 15, 'F')
        self.rect(9, 16, 15, 3, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 15)
        self.text(35, 19, 'HIA - HEALTH INSIGHTS REPORT')
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(138, 153, 173)
        self.text(35, 26, 'AI-Powered Biomarker Diagnostic Analysis')
        self.ln(30)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Health Insights Agent', 0, 0, 'C')

def clean_latin1(text):
    """Replace non-Latin-1 characters with ASCII equivalents to prevent PDF encoding errors."""
    if not text:
        return ""
    replacements = {
        "\u2013": "-",   # en-dash
        "\u2014": "--",  # em-dash
        "\x96": "-",     # en-dash CP1252
        "\u0096": "-",   # control character en-dash
        "\x95": "-",     # bullet CP1252
        "\u0095": "-",   # control character bullet
        "\x91": "'",     # left single quote CP1252
        "\u0091": "'",
        "\x92": "'",     # right single quote CP1252
        "\u0092": "'",
        "\x93": '"',     # left double quote CP1252
        "\u0093": '"',
        "\x94": '"',     # right double quote CP1252
        "\u0094": '"',
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2022": "-",   # bullet point
        "\u00b5": "u",   # micro symbol (µ)
        "\u03bc": "u",   # greek micro (μ)
        "\u2103": "C",   # Celsius
        "\u2109": "F",   # Fahrenheit
        "\u200b": "",    # zero-width space
        "\u00b1": "+/-", # plus-minus
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    # Force encode/decode to discard any remaining unencodable characters
    return text.encode('latin-1', 'replace').decode('latin-1')

def clean_markdown(text):
    """Strip markdown bold, italic, and header formatting tags for plain PDF rendering."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'_(.*?)_', r'\1', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    return text

def generate_pdf_report(patient_name, age, gender, report_text):
    """Compiles the report analysis markdown into a professional medical PDF."""
    patient_name = clean_latin1(str(patient_name))
    age = clean_latin1(str(age))
    gender = clean_latin1(str(gender))
    report_text = clean_latin1(report_text)

    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    
    # Patient Info Card Box
    pdf.set_fill_color(241, 245, 249) # Light slate box
    pdf.rect(10, 42, 190, 28, 'F')
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(10, 42, 190, 28, 'D')
    
    pdf.set_text_color(15, 23, 42)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.text(15, 49, "PATIENT NAME:")
    pdf.text(15, 56, "AGE:")
    pdf.text(15, 63, "GENDER:")
    
    pdf.set_font('Helvetica', '', 10)
    pdf.text(48, 49, str(patient_name))
    pdf.text(48, 56, f"{age} years")
    pdf.text(48, 63, str(gender))
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.text(115, 49, "ANALYSIS DATE:")
    pdf.text(115, 56, "DIAGNOSTIC STATUS:")
    
    pdf.set_font('Helvetica', '', 10)
    pdf.text(152, 49, datetime.now().strftime('%d-%m-%Y %H:%M'))
    pdf.set_text_color(16, 185, 129) # green
    pdf.text(160, 56, "SUCCESS / COMPLETE")
    
    # Write content
    pdf.set_y(80)
    pdf.set_text_color(30, 41, 59) # Slate 800 text
    
    lines = report_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue
            
        # Ignore horizontal rules and convert to lines
        if line.startswith('---'):
            pdf.set_draw_color(203, 213, 225)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)
            continue
            
        # Ignore diagnostic disclaimer note wrapper if empty
        if line == ">":
            continue
            
        cleaned_line = clean_markdown(line)
        
        # Check formatting headers
        if line.startswith('###'):
            pdf.set_font('Helvetica', 'B', 11)
            pdf.set_text_color(78, 140, 255) # Blue headers
            pdf.multi_cell(190, 6, cleaned_line.replace('###', '').strip(), 0, 'L')
            pdf.set_text_color(30, 41, 59)
            pdf.ln(1)
        elif line.startswith('##'):
            pdf.set_font('Helvetica', 'B', 12)
            pdf.set_text_color(20, 25, 35)
            pdf.multi_cell(190, 7, cleaned_line.replace('##', '').strip(), 0, 'L')
            pdf.set_text_color(30, 41, 59)
            pdf.ln(1)
        elif line.startswith('#'):
            pdf.set_font('Helvetica', 'B', 14)
            pdf.set_text_color(20, 25, 35)
            pdf.multi_cell(190, 8, cleaned_line.replace('#', '').strip(), 0, 'L')
            pdf.set_text_color(30, 41, 59)
            pdf.ln(2)
        elif (line.startswith('-') or line.startswith('*')) and not (line.startswith('**') or line.startswith('__')):
            pdf.set_font('Helvetica', '', 10)
            bullet_text = cleaned_line[1:].strip()
            # Draw a custom HIA blue bullet point block
            pdf.set_fill_color(78, 140, 255)
            pdf.rect(12, pdf.get_y() + 2, 2, 2, 'F')
            pdf.set_x(17)
            pdf.multi_cell(183, 5, bullet_text)
        else:
            pdf.set_font('Helvetica', '', 10)
            pdf.multi_cell(190, 5, cleaned_line)
            
    # Output raw PDF bytes (defensively compatible with both fpdf and fpdf2)
    pdf_out = pdf.output()
    if isinstance(pdf_out, str):
        return pdf_out.encode('latin-1')
    return bytes(pdf_out)
