import re
import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from xml.sax.saxutils import escape

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count):
        # Draw top banner
        self.setFillColor(colors.HexColor("#141923"))
        self.rect(0, A4[1] - 80, A4[0], 80, fill=True, stroke=False)
        
        # Medical cross logo indicator
        self.setFillColor(colors.HexColor("#4E8CFF"))
        self.rect(40, A4[1] - 50, 6, 20, fill=True, stroke=False)
        self.rect(33, A4[1] - 43, 20, 6, fill=True, stroke=False)
        
        # Header Text
        self.setFillColor(colors.white)
        self.setFont("Helvetica-Bold", 15)
        self.drawString(70, A4[1] - 42, "HIA - HEALTH INSIGHTS REPORT")
        
        self.setFillColor(colors.HexColor("#8A99AD"))
        self.setFont("Helvetica", 10)
        self.drawString(70, A4[1] - 56, "AI-Powered Biomarker Diagnostic Analysis")
        
        # Footer
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(40, 50, A4[0] - 40, 50)
        
        self.setFillColor(colors.HexColor("#64748B"))
        self.setFont("Helvetica-Oblique", 8)
        self.drawString(40, 35, "Generated by Health Insights Agent")
        
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(A4[0] - 40, 35, page_text)

def clean_latin1(text):
    """Replace unsupported characters with clean ASCII/HTML equivalents to prevent PDF encoding errors in Helvetica."""
    if not text:
        return ""
    replacements = {
        "\u2013": "-",   # en-dash
        "\u2014": "--",  # em-dash
        "\x96": "-",
        "\u0096": "-",
        "\x95": "-",
        "\u0095": "-",
        "\x91": "'",
        "\u0091": "'",
        "\x92": "'",
        "\u0092": "'",
        "\x93": '"',
        "\u0093": '"',
        "\x94": '"',
        "\u0094": '"',
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2022": "&bull;",   # bullet point HTML entity
        "\u00b5": "&micro;",  # micro symbol entity
        "\u03bc": "&micro;",  # greek micro entity
        "\u2103": "C",
        "\u2109": "F",
        "\u200b": "",
        "\u00b1": "&plusmn;", # plus-minus entity
        "✅": "[CORRECT] ",
        "✔": "[OK] ",
        "⚠️": "[ALERT] ",
        "💊": "[THERAPY] ",
        "■": "&bull;",
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
        
    # Strip any remaining unencodable characters for Helvetica
    return text.encode('latin-1', 'ignore').decode('latin-1')

def escape_and_format_md(text):
    """Escape XML characters and convert markdown formatting to ReportLab HTML-like tags."""
    if not text:
        return ""
    
    # 1. Escape XML entities FIRST to prevent ReportLab parser crashes, and before we inject our own HTML entities/tags
    text = escape(text)  # escapes <, >, and &
    
    # 2. Clean unsupported characters and emojis (injects &bull; etc.)
    text = clean_latin1(text)
    
    # 3. Clean LaTeX math blocks e.g. $(500~mg/day)$ to 500 mg/day
    text = re.sub(r'\$\((.*?)\)\$', lambda m: m.group(1).replace('~', ' '), text)
    text = re.sub(r'\$(.*?)\$', lambda m: m.group(1).replace('~', ' '), text)
    
    # 4. Inject formatting tags
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'__(.*?)__', r'<b>\1</b>', text)
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    text = re.sub(r'_(.*?)_', r'<i>\1</i>', text)
    text = re.sub(r'`(.*?)`', r'<i>\1</i>', text)
    
    return text

def create_patient_info_table(patient_name, age, gender):
    styles = getSampleStyleSheet()
    label_style = ParagraphStyle('CardLabel', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, textColor=colors.HexColor("#0F172A"))
    val_style = ParagraphStyle('CardVal', parent=styles['Normal'], fontName='Helvetica', fontSize=9, textColor=colors.HexColor("#334155"))
    status_style = ParagraphStyle('CardStatus', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, textColor=colors.HexColor("#10B981"))
    
    info_data = [
        [
            Paragraph("<b>PATIENT NAME:</b>", label_style),
            Paragraph(patient_name, val_style),
            Paragraph("<b>ANALYSIS DATE:</b>", label_style),
            Paragraph(datetime.now().strftime('%d-%m-%Y %H:%M'), val_style)
        ],
        [
            Paragraph("<b>AGE:</b>", label_style),
            Paragraph(f"{age} years" if str(age).isdigit() else str(age), val_style),
            Paragraph("<b>DIAGNOSTIC STATUS:</b>", label_style),
            Paragraph("SUCCESS / COMPLETE", status_style)
        ],
        [
            Paragraph("<b>GENDER:</b>", label_style),
            Paragraph(gender, val_style),
            Paragraph("", label_style),
            Paragraph("", val_style)
        ]
    ]
    
    info_table = Table(info_data, colWidths=[110, 147, 120, 138])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F1F5F9")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
        ('RIGHTPADDING', (0,0), (-1,-1), 10),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    return info_table

def generate_pdf_report(patient_name, age, gender, report_text):
    """Compiles the report analysis markdown into a professional dynamic flowable PDF using ReportLab."""
    patient_name = clean_latin1(str(patient_name))
    age = clean_latin1(str(age))
    gender = clean_latin1(str(gender))

    buffer = io.BytesIO()
    
    # Margins setup to avoid header banner and footer overlap
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=110, bottomMargin=70)
    
    styles = getSampleStyleSheet()
    
    h1_style = ParagraphStyle('Heading1', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=14, spaceAfter=12, textColor=colors.HexColor("#141923"))
    h2_style = ParagraphStyle('Heading2', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=12, spaceBefore=10, spaceAfter=8, textColor=colors.HexColor("#1E293B"))
    h3_style = ParagraphStyle('Heading3', parent=styles['Heading3'], fontName='Helvetica-Bold', fontSize=11, spaceBefore=8, spaceAfter=6, textColor=colors.HexColor("#4E8CFF"))
    
    normal_style = ParagraphStyle('NormalStyle', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, spaceAfter=6, textColor=colors.HexColor("#1E293B"))
    
    bullet_style = ParagraphStyle('BulletStyle', parent=normal_style, leftIndent=20, firstLineIndent=-10, spaceAfter=4)
    
    story = []
    
    # Add Patient Info Card
    story.append(create_patient_info_table(patient_name, age, gender))
    story.append(Spacer(1, 20))
    
    # Parse Markdown lines
    lines = report_text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
            continue
            
        if line.startswith('---'):
            hr = Table([['']], colWidths=[doc.width])
            hr.setStyle(TableStyle([
                ('LINEABOVE', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 0),
            ]))
            story.append(Spacer(1, 6))
            story.append(hr)
            story.append(Spacer(1, 10))
            continue
            
        if line == ">":
            continue
            
        if line.startswith('###'):
            text = escape_and_format_md(line.replace('###', '').strip())
            story.append(Paragraph(text, h3_style))
        elif line.startswith('##'):
            text = escape_and_format_md(line.replace('##', '').strip())
            story.append(Paragraph(text, h2_style))
        elif line.startswith('#'):
            text = escape_and_format_md(line.replace('#', '').strip())
            story.append(Paragraph(text, h1_style))
        elif (line.startswith('-') or line.startswith('*')) and not (line.startswith('**') or line.startswith('__')):
            text = escape_and_format_md(line[1:].strip())
            story.append(Paragraph(f"&bull; {text}", bullet_style))
        elif line.startswith('>'):
            text = escape_and_format_md(line[1:].strip())
            quote_style = ParagraphStyle('Quote', parent=normal_style, fontName='Helvetica-Oblique', textColor=colors.HexColor("#64748B"), leftIndent=15)
            story.append(Paragraph(text, quote_style))
        else:
            text = escape_and_format_md(line)
            story.append(Paragraph(text, normal_style))
            
    # Build PDF and return bytes
    doc.build(story, canvasmaker=NumberedCanvas)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
