import groq
import os
from enum import Enum
import logging
import time
import ast
from datetime import datetime

logger = logging.getLogger(__name__)

from services.db_service import get_config_db

def get_groq_api_key():
    key = get_config_db("GROQ_API_KEY")
    if key and "your-groq" not in key and key.strip() != "":
        return key.strip()
    
    try:
        key = os.environ.get("GROQ_API_KEY")
        if key and "your-groq" not in key and key.strip() != "":
            return key.strip()
    except Exception:
        pass
    return None

def generate_mock_analysis(data):
    patient_name = data.get("patient_name", "Valued Patient") if isinstance(data, dict) else "Valued Patient"
    age = data.get("age", 35) if isinstance(data, dict) else 35
    gender = data.get("gender", "Unknown") if isinstance(data, dict) else "Unknown"
    report = data.get("report", "") if isinstance(data, dict) else str(data)
    
    report_lower = report.lower()
    findings = []
    recommendations = []
    
    if "glucose" in report_lower or "sugar" in report_lower:
        findings.append("• **Blood Glucose Levels**: Checked. Levels appear to be within a manageable range. If there's history of fluctuation, continue monitoring fasting glucose.")
        recommendations.append("- **Dietary**: Limit refined carbohydrates and high-glycemic index foods. Focus on whole grains and high-fiber foods.")
    if "cholesterol" in report_lower or "lipid" in report_lower or "ldl" in report_lower or "hdl" in report_lower:
        findings.append("• **Lipid Profile (Cholesterol)**: Analyzed. HDL (good cholesterol) and LDL (bad cholesterol) balance is critical. Ensure active cardiovascular exercise to boost HDL.")
        recommendations.append("- **Cardiovascular**: Aim for 30 minutes of moderate aerobic activity 5 days a week to support healthy cholesterol levels.")
    if "hemoglobin" in report_lower or "hb" in report_lower or "anemia" in report_lower:
        findings.append("• **Hemoglobin (Hb)**: Analyzed. Normal hemoglobin levels support active cellular oxygenation. If slightly low, focus on iron-rich foods.")
        recommendations.append("- **Nutritional**: Incorporate iron-rich foods (spinach, lentils, red meat) paired with Vitamin C to enhance absorption.")
    if "creatinine" in report_lower or "kidney" in report_lower:
        findings.append("• **Kidney Function (Creatinine)**: Checked. Keeping hydrated is key to maintaining proper glomerular filtration.")
        recommendations.append("- **Hydration**: Ensure adequate daily water intake (approx. 2-3 liters) and limit excess sodium.")
        
    if not findings:
        findings.append("• **General Biomarker Scan**: All primary hematology and metabolic panels checked and appear stable.")
        findings.append("• **Immune markers**: White Blood Cell (WBC) count and differential check suggests normal baseline immune response.")
        recommendations.append("- **Routine Care**: Maintain a balanced plate containing clean protein, healthy fats, and rich antioxidants.")
        recommendations.append("- **Wellness Check**: Repeat blood panels in 6-12 months for routine monitoring.")

    analysis_content = f"""# 🩺 Comprehensive Health Report Analysis
    
## Patient Profile
- **Name**: {patient_name}
- **Age**: {age}
- **Gender**: {gender}
- **Date**: {datetime.now().strftime('%B %d, %Y')}

---

## 📊 Key Findings and Observations
{chr(10).join(findings)}

---

## 🥗 Personalized Lifestyle Recommendations
{chr(10).join(recommendations)}

---

## ⚕️ Specialist Advice
- Consult a certified healthcare provider to review these findings in the context of your overall medical history.
- Do not make any drastic changes to your medications or diet without professional guidance.

---
*Note: This is a simulated high-quality analysis generated by HIA (Health Insights Agent) in Demo/Mock Mode. For clinical use, configure the Groq key in the Admin Panel.*
"""
    return analysis_content

class MockMessage:
    def __init__(self, content):
        self.content = content

class MockChoice:
    def __init__(self, content):
        self.message = MockMessage(content)

class MockCompletion:
    def __init__(self, content):
        self.choices = [MockChoice(content)]

class MockCompletions:
    def create(self, model, messages, temperature, max_tokens):
        user_prompt = ""
        for msg in messages:
            if msg.get("role") == "user":
                user_prompt = msg.get("content", "")
                break
        
        # Parse data back to dict if it was stringified dict
        data = {}
        try:
            data = ast.literal_eval(user_prompt)
        except Exception:
            data = {"report": user_prompt}
            
        content = generate_mock_analysis(data)
        return MockCompletion(content)

class MockChat:
    def __init__(self):
        self.completions = MockCompletions()

class MockGroqClient:
    def __init__(self, api_key=None):
        self.chat = MockChat()

class ModelTier(Enum):
    PRIMARY = "primary"
    SECONDARY = "secondary" 
    TERTIARY = "tertiary"
    FALLBACK = "fallback"

class ModelManager:
    """
    Manages AI model selection, fallback, and rate limits.
    Implements an agent-based approach for model management.
    """
    
    MODEL_CONFIG = {
        ModelTier.PRIMARY: {
            "provider": "groq",
            "model": "meta-llama/llama-4-maverick-17b-128e-instruct",
            "max_tokens": 2000,
            "temperature": 0.7
        },
        ModelTier.SECONDARY: {
            "provider": "groq", 
            "model": "llama-3.3-70b-versatile",
            "max_tokens": 2000,
            "temperature": 0.7
        },
        ModelTier.TERTIARY: {
            "provider": "groq",
            "model": "llama-3.1-8b-instant",
            "max_tokens": 2000, 
            "temperature": 0.7
        },
        ModelTier.FALLBACK: {
            "provider": "groq",
            "model": "llama3-70b-8192",
            "max_tokens": 2000,
            "temperature": 0.7
        }
    }
    
    def __init__(self):
        self.clients = {}
        self._initialize_clients()

    def _initialize_clients(self):
        """Initialize API clients for each provider."""
        key = get_groq_api_key()
        if not key:
            self.clients["groq"] = MockGroqClient()
        else:
            try:
                self.clients["groq"] = groq.Groq(api_key=key)
            except Exception as e:
                logger.error(f"Failed to initialize Groq client: {str(e)}")
                self.clients["groq"] = MockGroqClient()

    def generate_analysis(self, data, system_prompt, retry_count=0):
        """
        Generate analysis using the best available model with automatic fallback.
        Implements agent-based decision making for model selection.
        """
        if retry_count > 3:
            return {"success": False, "error": "All models failed after multiple retries"}

        # Determine which model tier to use based on retry count
        if retry_count == 0:
            tier = ModelTier.PRIMARY
        elif retry_count == 1:
            tier = ModelTier.SECONDARY
        elif retry_count == 2:
            tier = ModelTier.TERTIARY
        else:
            tier = ModelTier.FALLBACK
            
        model_config = self.MODEL_CONFIG[tier]
        provider = model_config["provider"]
        model = model_config["model"]
        
        # Check if we have a client for this provider
        if provider not in self.clients:
            logger.error(f"No client available for provider: {provider}")
            return self.generate_analysis(data, system_prompt, retry_count + 1)
            
        try:
            client = self.clients[provider]
            logger.info(f"Attempting generation with {provider} model: {model}")
            
            if provider == "groq":
                completion = client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": str(data)}
                    ],
                    temperature=model_config["temperature"],
                    max_tokens=model_config["max_tokens"]
                )
                
                return {
                    "success": True,
                    "content": completion.choices[0].message.content,
                    "model_used": f"{provider}/{model}"
                }
                
        except Exception as e:
            error_message = str(e).lower()
            logger.warning(f"Model {model} failed: {error_message}")
            
            # Check for rate limit errors
            if "rate limit" in error_message or "quota" in error_message:
                # Wait briefly before retrying with a different model
                time.sleep(2)
            
            # Try next model in hierarchy
            return self.generate_analysis(data, system_prompt, retry_count + 1)
            
        return {"success": False, "error": "Analysis failed with all available models"}
